name: build-update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup non-root builder
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
          chmod 440 /etc/sudoers.d/builder
          mkdir -p /home/builder/.cache /home/builder/.config
          chown -R builder:builder /home/builder

      - name: Install base dependencies
        run: |
          pacman -Sy --noconfirm git base-devel jq

      - name: Install yay and AUR deps
        run: |
          sudo -u builder git clone https://aur.archlinux.org/yay.git /home/builder/yay
          sudo -u builder makepkg -si --noconfirm -C /home/builder/yay
          sudo -u builder yay -S --noconfirm electron25

      - name: Get latest AUR version
        id: aur
        run: |
          AUR_JSON=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=info&arg=claude-desktop")
          echo "aur_version=$(echo $AUR_JSON | jq -r '.results.Version')" >> $GITHUB_ENV

      - name: Get latest GitHub release version
        id: gh
        run: |
          GH_VERSION=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq -r '.tag_name')
          echo "gh_version=$GH_VERSION" >> $GITHUB_ENV

      - name: Compare versions
        id: compare
        run: |
          if [ "$aur_version" = "$gh_version" ]; then
            echo "build=false" >> $GITHUB_ENV
          else
            echo "build=true" >> $GITHUB_ENV

      - name: Build claude-desktop
        if: env.build == 'true'
        run: |
          sudo -u builder git clone https://aur.archlinux.org/claude-desktop.git /home/builder/claude-desktop
          sudo -u builder makepkg -sci --noconfirm -C /home/builder/claude-desktop

      - name: Upload package as release
        if: env.build == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: /home/builder/claude-desktop/*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
